"""sincronizar piezas de lote, consumos de pieza, precio de compra y observacion de pagos

Revision ID: 70522830813f
Revises: 7426c78494c4
Create Date: 2026-09-24 15:16:02.931349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70522830813f'
down_revision: Union[str, None] = '7426c78494c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piezas_lote_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('codigo_identificador', sa.String(length=60), nullable=False),
    sa.Column('ancho_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('largo_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('espesor_mm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('capacidad_inicial', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_restante', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('costo_adquisicion', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('disponible', 'en_uso', 'agotado', name='estado_pieza', native_enum=False, length=20), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=False),
    sa.Column('maquina_asignada', sa.String(length=120), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_termino', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_piezas_lote_material_codigo_identificador'), 'piezas_lote_material', ['codigo_identificador'], unique=False)
    op.create_index(op.f('ix_piezas_lote_material_material_id'), 'piezas_lote_material', ['material_id'], unique=False)
    op.create_table('consumos_pieza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pieza_id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('trabajo_descripcion', sa.String(length=250), nullable=False),
    sa.Column('cantidad_consumida', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_anterior', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_nuevo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_cobrado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('merma_desperdicio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ),
    sa.ForeignKeyConstraint(['pieza_id'], ['piezas_lote_material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumos_pieza_orden_id'), 'consumos_pieza', ['orden_id'], unique=False)
    op.create_index(op.f('ix_consumos_pieza_pieza_id'), 'consumos_pieza', ['pieza_id'], unique=False)
    # RF-63: estas cinco columnas son NOT NULL sobre tablas que ya pueden
    # tener filas (materiales/orden_pagos existen desde el esquema inicial).
    # `server_default` es indispensable aquí, no cosmético: sin él, Postgres
    # rechaza el ALTER TABLE en cuanto la tabla tiene una sola fila
    # (`column ... contains null values`). Con `server_default`, el mismo
    # valor que ya usa el modelo como default de Python (`default=...`) se
    # aplica también a nivel de base para las filas existentes, así que la
    # migración queda segura sobre una base vacía (CI) y sobre una restaurada
    # con datos reales (el escenario de recuperación de desastres).
    op.add_column('materiales', sa.Column('precio_compra', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('materiales', sa.Column('ubicacion_estante', sa.String(length=120), server_default='', nullable=False))
    op.add_column('materiales', sa.Column('tipo_formato', sa.Enum('continuo_rollo', 'plancha_rigida', 'unidad_pieza', 'quimico_tinta', name='tipo_formato_material', native_enum=False, length=25), server_default='unidad_pieza', nullable=False))
    op.add_column('materiales', sa.Column('ancho_predeterminado_m', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('materiales', sa.Column('largo_predeterminado_m', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('materiales', sa.Column('espesor_mm', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('orden_pagos', sa.Column('estado_pago', sa.Enum('conforme', 'observado', 'anulado', name='estado_pago', native_enum=False, length=15), server_default='conforme', nullable=False))
    op.add_column('orden_pagos', sa.Column('motivo_observacion', sa.Enum('yape_falso', 'billete_falso', 'voucher_no_ubicado', 'cobro_duplicado', 'error_digitacion', 'otro', name='motivo_observacion_pago', native_enum=False, length=30), nullable=True))
    op.add_column('orden_pagos', sa.Column('nota_observacion', sa.Text(), server_default='', nullable=False))
    op.add_column('orden_pagos', sa.Column('observado_por', sa.Integer(), nullable=True))
    op.add_column('orden_pagos', sa.Column('observado_en', sa.DateTime(timezone=True), nullable=True))
    # RF-64: se nombra explícitamente (igual que el nombre que Postgres le
    # asigna por convención propia a un FK sin nombre, `<tabla>_<columna>_fkey`,
    # que es el que ya quedó grabado en producción) para que `downgrade()`
    # sepa qué constraint borrar. Con `None` (autogenerado), Alembic no puede
    # reconstruir ese nombre al revertir y el downgrade queda roto sin remedio.
    op.create_foreign_key('orden_pagos_observado_por_fkey', 'orden_pagos', 'usuarios', ['observado_por'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orden_pagos_observado_por_fkey', 'orden_pagos', type_='foreignkey')
    op.drop_column('orden_pagos', 'observado_en')
    op.drop_column('orden_pagos', 'observado_por')
    op.drop_column('orden_pagos', 'nota_observacion')
    op.drop_column('orden_pagos', 'motivo_observacion')
    op.drop_column('orden_pagos', 'estado_pago')
    op.drop_column('materiales', 'espesor_mm')
    op.drop_column('materiales', 'largo_predeterminado_m')
    op.drop_column('materiales', 'ancho_predeterminado_m')
    op.drop_column('materiales', 'tipo_formato')
    op.drop_column('materiales', 'ubicacion_estante')
    op.drop_column('materiales', 'precio_compra')
    op.drop_index(op.f('ix_consumos_pieza_pieza_id'), table_name='consumos_pieza')
    op.drop_index(op.f('ix_consumos_pieza_orden_id'), table_name='consumos_pieza')
    op.drop_table('consumos_pieza')
    op.drop_index(op.f('ix_piezas_lote_material_material_id'), table_name='piezas_lote_material')
    op.drop_index(op.f('ix_piezas_lote_material_codigo_identificador'), table_name='piezas_lote_material')
    op.drop_table('piezas_lote_material')
    # ### end Alembic commands ###
