"""esquema inicial

Revision ID: 7426c78494c4
Revises: 
Create Date: 2026-09-12 08:38:11.437705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7426c78494c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('persona', 'empresa', name='tipo_cliente', native_enum=False, length=10), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.Column('es_corporativo', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('propio', 'servicio', 'subcontratado', name='tipo_producto', native_enum=False, length=15), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=True)
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('abreviatura', sa.String(length=10), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'subgerente', 'secretaria', 'disenadora', 'operario', name='rol_usuario', native_enum=False, length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('sesion_version', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('auditoria',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.Enum('crear', 'editar', 'eliminar', 'cambio_estado', 'pago', 'ajuste_stock', 'sesion', 'cierre_caja', name='tipo_evento_auditoria', native_enum=False, length=20), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=60), nullable=False),
    sa.Column('registro_id', sa.String(length=40), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.Column('valores_anteriores', sa.JSON(), nullable=True),
    sa.Column('valores_nuevos', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_fecha'), 'auditoria', ['fecha'], unique=False)
    op.create_table('cierres_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('unidad_negocio', sa.Enum('imprenta', 'gigantografias', name='unidad_negocio', native_enum=False, length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('monto_efectivo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_yape', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_transferencia', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('cerrado', 'congelado', name='estado_cierre', native_enum=False, length=15), nullable=False),
    sa.Column('validado_por', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['validado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', 'unidad_negocio', 'usuario_id', name='cierre_unico_dia_unidad_usuario')
    )
    op.create_index(op.f('ix_cierres_caja_fecha'), 'cierres_caja', ['fecha'], unique=False)
    op.create_table('materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('alerta_minima', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dias_reabastecimiento', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiales_nombre'), 'materiales', ['nombre'], unique=True)
    op.create_table('ordenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('contrato', 'proforma', name='tipo_documento', native_enum=False, length=10), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('asignado_a', sa.Integer(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('unidad_negocio', sa.Enum('imprenta', 'gigantografias', name='unidad_negocio', native_enum=False, length=20), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'en_diseno', 'aprobado', 'en_produccion', 'finalizada', 'entregada', 'cancelada', name='estado_orden', native_enum=False, length=20), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=False),
    sa.Column('incluye_igv', sa.Boolean(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('motivo_descuento', sa.String(length=200), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('adelanto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pagado_totalmente', sa.Boolean(), nullable=False),
    sa.Column('metodo_pago_adelanto', sa.Enum('efectivo', 'yape', 'transferencia', name='metodo_pago', native_enum=False, length=15), nullable=False),
    sa.Column('finalizada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entregada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_estado'), 'ordenes', ['estado'], unique=False)
    op.create_table('movimientos_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_resultante', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('motivo', sa.Enum('reserva', 'liberacion', 'merma', 'devolucion', 'ajuste_manual', name='motivo_movimiento', native_enum=False, length=20), nullable=False),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_stock_material_id'), 'movimientos_stock', ['material_id'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_orden_id'), 'movimientos_stock', ['orden_id'], unique=False)
    op.create_table('orden_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('ancho_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('alto_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orden_items_orden_id'), 'orden_items', ['orden_id'], unique=False)
    op.create_table('orden_materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('unidad', sa.String(length=10), nullable=False),
    sa.Column('cantidad_estimada', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cantidad_real', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orden_materiales_orden_id'), 'orden_materiales', ['orden_id'], unique=False)
    op.create_table('orden_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'yape', 'transferencia', name='metodo_pago', native_enum=False, length=15), nullable=False),
    sa.Column('tipo', sa.Enum('adelanto', 'saldo', name='tipo_pago', native_enum=False, length=10), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('referencia', sa.String(length=120), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orden_pagos_orden_id'), 'orden_pagos', ['orden_id'], unique=False)
    op.create_table('producto_materiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'material_id', name='producto_material_unico')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_materiales')
    op.drop_index(op.f('ix_orden_pagos_orden_id'), table_name='orden_pagos')
    op.drop_table('orden_pagos')
    op.drop_index(op.f('ix_orden_materiales_orden_id'), table_name='orden_materiales')
    op.drop_table('orden_materiales')
    op.drop_index(op.f('ix_orden_items_orden_id'), table_name='orden_items')
    op.drop_table('orden_items')
    op.drop_index(op.f('ix_movimientos_stock_orden_id'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_material_id'), table_name='movimientos_stock')
    op.drop_table('movimientos_stock')
    op.drop_index(op.f('ix_ordenes_estado'), table_name='ordenes')
    op.drop_table('ordenes')
    op.drop_index(op.f('ix_materiales_nombre'), table_name='materiales')
    op.drop_table('materiales')
    op.drop_index(op.f('ix_cierres_caja_fecha'), table_name='cierres_caja')
    op.drop_table('cierres_caja')
    op.drop_index(op.f('ix_auditoria_fecha'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('unidades')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
